FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx_sticky.conf /etc/nginx/nginx_sticky.conf
COPY nginx_weighted.conf /etc/nginx/nginx_weighted.conf
COPY nginx_url.conf /etc/nginx/nginx_url.conf
EXPOSE 80
